### ISSUE TITLE
User Interface not opening using system IP

### ISSUE THREAD

**Issue by tamalindia** [linagora/linshare-ui-admin#7]
HI,

I have created the server and the admin interface is working fine. I am using the system IP to opening admin portal. That means when I am opening the system IP in the browser it will open Linshare Admin interface/portal. But how do I open user interface using the system IP? Any help will be appreciated.

Thanks in advance.

Regards

**Comment by fmartin-linagora** [comment]
Hi,
We are using the vhost linshare.local and admin.linshare.local to be able to join the LinShare server without the IP, on the same port. If you don't you just need to listen both your vhost on two different ports.

**Comment by hyvan29444** [comment]
Hello everyone.
I just installed version 4.1.2 of linshare under debian 10 and my admin interface is incomplete. could you help me please ?
I followed the installation procedure on this link 
https://github.com/linagora/linshare/blob/master/documentation/FR/installation/linshare-install-debian.md
![image](https://user-images.githubusercontent.com/83696761/117120283-6e76a880-ad93-11eb-862f-9715bdf671c6.png)

**Comment by fmartin-linagora** [comment]
Hi,
There is no login popup, so it means that the backend/api server is not responding properly. You need to look to the logs of your tomcat, see /var/log/tomcat/catalina.out.

**Comment by hyvan29444** [comment]
Thank you for your reply.
I looked in the log file, I found some problems but I can not locate where the error came from in the file configuration. Especially since we can see at the end of the logs that it has started
![image](https://user-images.githubusercontent.com/83696761/117122027-aed72600-ad95-11eb-8a39-b47610574a1b.png)
![image](https://user-images.githubusercontent.com/83696761/117122092-c9a99a80-ad95-11eb-9c61-878ece6adaa8.png)

**Comment by fmartin-linagora** [comment]
The tomcat is telling you linshare.war was not deployed because there were some errors, these errors are in this file, a bit above these messages.

**Comment by hyvan29444** [comment]
Hi.
I haven't always been able to solve my problem with the admin interface popup.
I would like to know if the problem could come from a conflict between java 11 and tomcat. Because I searched a little and it seems to have some problems with the jre.
please could you tell me if that can be the case so that I can narrow down my research on the incident.

**Comment by fmartin-linagora** [comment]
As I told you, you have probably an error message in the logs of the tomcat. Can you send me the catalina.out ? maybe I will be able to see it.

**Comment by hyvan29444** [comment]
Thank you for your help.
I am sending you my log file here.
[catalina.txt](https://github.com/linagora/linshare-ui-admin/files/6436062/catalina.txt)

**Comment by fmartin-linagora** [comment]
AS you can see you have the following error:
```
[2021-05-06 11:36:44] [info] [ERROR]:main:20210506.113644:org.springframework.web.context.ContextLoader:initWebApplicationContext:Context initialization failed
```

And just one line above, you have:
```
[2021-05-06 11:36:44] [info] [WARN]:main:20210506.113644:org.springframework.web.context.support.XmlWebApplicationContext:refresh:Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'dataSourceHibernate' defined in file [/var/lib/tomcat9/webapps/linshare/WEB-INF/classes/springContext-datasource.xml]: Could not resolve placeholder 'LINSHARE_HOME' in value "jdbc:h2:file:${LINSHARE_HOME}/var/lib/linshare/db/linshare"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'LINSHARE_HOME' in value "jdbc:h2:file:${LINSHARE_HOME}/var/lib/linshare/db/linshare"
```

It means you did not provide the configuration file to the Tomcat. the configuration key to the file (-Dlinshare.config.path) is missing, the path is wrong or the tomcat does not have read access. So the Tomcat is trying to access to the default linshare.properties file which contains an environement variable named LINSHARE_HOME for development purpose.

Of course in prodution, you must not rely on the embedded configuation file. You must provide yours.

See the documentation [here](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-debian.md#tomcat-installation)

**Comment by hyvan29444** [comment]
Hi.
Please excuse me for not having made a return following your remark.
I still have not succeeded, but I have switched to an installation on the centos and all are working.

I would just like to know if it is possible to change the notification email address and the download link of a file?
Thank you in advance for your reply

**Comment by fmartin-linagora** [comment]
Hi,
Yes you can do it, you have go to the admin panel, menu Functionalities and the you need to click on the functionality named 'Domain', see above:
![image](https://user-images.githubusercontent.com/6229766/121395550-d8660d00-c952-11eb-98f8-1b5fd7ea7cd8.png)

You can configure the default value on the root domain, and then override it (if needed) in sub domains.

Regards,

**Comment by hyvan29444** [comment]
Hi.
Thank you very much for your responsiveness and your response.
 I was able to change these settings.
Thanks again

**Comment by hyvan29444** [comment]
I'm really sorry to bother you, but this will be my last question.
Can I add other extensions (for example :  cryptographic file extensions) in addition to the extensions that are already present?

**Comment by fmartin-linagora** [comment]
Sorry, the list of supported extension/mime types can't be updated.

**Comment by hyvan29444** [comment]
ok thank you for your answer
